#include "peerclass.h"

// shameslessly generated by le chat gpt
void print_open_fds()
{
	char path[PATH_MAX];
	char link_target[PATH_MAX];
	ssize_t len;

	DIR *dir = opendir("/proc/self/fd");
	if (!dir)
	{
		perror("opendir");
		return;
	}
	printf("Open file descriptors:\n");
	struct dirent *entry;
	while ((entry = readdir(dir)) != NULL) {
		if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0)
			continue;
		snprintf(path, sizeof(path), "/proc/self/fd/%s", entry->d_name);
		len = readlink(path, link_target, sizeof(link_target) - 1);
		if (len != -1) {
			link_target[len] = '\0';
			printf("FD %s -> %s\n", entry->d_name, link_target);
		} else {
			printf("FD %s -> [error: %s]\n", entry->d_name, strerror(errno));
		}
	}
	printf("\n");
	closedir(dir);
}
